### ISSUE TITLE
使用3.8.1打开MKFramework项目直接卡死升级在加载资源界面

### ISSUE THREAD

**Issue by 929496959** [1226085293/MKFramework#5]
使用3.8.1打开MKFramework项目直接卡死升级在加载资源界面

**Comment by 929496959** [comment]
![CocosCreator_2DVMgfdCkO](https://github.com/1226085293/MKFramework/assets/49754986/e4515652-e67f-457b-819c-8d4ac1fbadbc)

**Comment by 1226085293** [comment]
未复现，可以命令行启动查看是否有报错

![image](https://github.com/1226085293/MKFramework/assets/45589707/ef90f494-6c92-4534-a112-15c4daaa223c)
