### ISSUE TITLE
🐛[Bug] 使用 Preview in Editor 似乎 open() 跟 close() 等沒有正常呼叫

### ISSUE THREAD

**Issue by SyaoranChang** [1226085293/MKFramework#50]
#### 您使用的版本？ | Your usage version?

CocosCreator：3.8.4

MKFramework：1.0.3

#### 您期望的结果是怎样的？ | What is your expected outcome? 按鈕文字變成 摘星星，按下要切換為 stars_main 的場景開始遊戲

**Comment by 1226085293** [comment]
编辑器预览模式是不完善的功能，不能做到和实际运行一致，所以尽可能使用 chrome 或者模拟器调试
