### ISSUE TITLE
npx mk-install 执行报错

### ISSUE THREAD

**Issue by Xzhiming** [1226085293/MKFramework#9]
![image](https://github.com/1226085293/MKFramework/assets/25840064/8867dc4d-4be0-4f94-959f-c455a0e2b3f6)

**Comment by 1226085293** [comment]
> ![图像](https://user-images.githubusercontent.com/25840064/284439690-8867dc4d-4be0-4f94-959f-c455a0e2b3f6.png)

你好，已经修复，请重新执行安装命令 `npm i @muzzik/mk-install`

感谢反馈

**Comment by Xzhiming** [comment]
刚试了，不行。还是那样

**Comment by 1226085293** [comment]
你可以使用 `npm -g list` 查看安装的包版本，如果小于 1.0.3，那么不是最新版本

可以尝试先执行 `npm uninstall -g @muzzik/mk-install` 后再执行 `npm i -g @muzzik/mk-install`

**Comment by Xzhiming** [comment]
嗯  版本不对。卸载重装还是1.0.2

**Comment by Xzhiming** [comment]
npm update -g @muzzik/mk-install

**Comment by Xzhiming** [comment]
npm update -g @muzzik/mk-install 
更新不下来呢，还是1.0.2

**Comment by 1226085293** [comment]
检查下自己的网络情况，尽可能用梯子，需要命令成功执行完成且无报错
